export const LoginTypes = {
  secret: "secret",
  walletConnect: "wallet-connect",
  public: "public",
  ledger: "ledger",
  lobstr: "lobstr",
  walletKit: "wallet-kit",
};

export const AUTH_ACTIONS = {
  LOGIN_START: "LOGIN_START",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  CLEAR_LOGIN_ERROR: "CLEAR_LOGIN_ERROR",
  LOGOUT: "LOGOUT",
  FEDERATION_RESOLVE_START: "FEDERATION_RESOLVE_START",
  FEDERATION_RESOLVE_SUCCESS: "FEDERATION_RESOLVE_SUCCESS",
  FEDERATION_RESOLVE_FAIL: "FEDERATION_RESOLVE_FAIL",
  UPDATE_ACCOUNT: "UPDATE_ACCOUNT",
  ENABLE_REDIRECT: "ENABLE_REDIRECT",
  DISABLE_REDIRECT: "DISABLE_REDIRECT",
  ADD_AUTH_CALLBACK: "ADD_AUTH_CALLBACK",
  REMOVE_AUTH_CALLBACK: "REMOVE_AUTH_CALLBACK",
};
